apiVersion: v1
kind: Service
metadata:
  name: opentunnel-frontend-lb
spec:
  selector:
    app: opentunnel-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9000
      name: app
    - protocol: TCP
      port: 80
      targetPort: 9005
      name: app-http
  type: NodePort