apiVersion: v1
kind: Service
metadata:
  name: opentunnel-registrator-lb
spec:
  selector:
    app: opentunnel-registrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
      name: app
  type: NodePort