apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentunnel-backend
  labels:
    app: opentunnel-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opentunnel-backend
  template:
    metadata:
      labels:
        app: opentunnel-backend
    spec:
      containers:
        - name: opentunnel
          image: ex3ndr/opentunnel:v24
          command: ['node', './cli.js']
          args:
            [
              'backend',
              'iSDgI2m6iXHyoWrhX8e+Uv5bgw9DYbhssKtJrhMVAW0=',
              '-s',
              'opentunnel-nats',
            ]
          ports:
            - containerPort: 9001
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
