apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentunnel-frontend
  labels:
    app: opentunnel-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opentunnel-frontend
  template:
    metadata:
      labels:
        app: opentunnel-frontend
    spec:
      containers:
        - name: opentunnel
          image: ex3ndr/opentunnel:v25
          command: ["node", "./cli.js"]
          args: ["frontend", '-s', 'opentunnel-nats']
          ports:
            - containerPort: 9000
            - containerPort: 9005
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9002
